GET http://localhost:3001/api/blogs

###############

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer 

{
    "author": "Author McAuthorface",
    "url": "www.www.www",
    "title": "including word react to make sure this gets returned in search query test"
}
############

DELETE http://localhost:3001/api/blogs/2
Authorization: bearer 

#########

PUT http://localhost:3001/api/blogs/15
Content-Type: application/json

{
    "likes": 441
}

#########

GET http://localhost:3001/api/blogs?search=react