GET http://localhost:3001/api/blogs

###############

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZvb0Bmb28uY29tIiwiaWQiOjEsImlhdCI6MTY3Nzc4ODE1MCwiZXhwIjoxNjc4MTQ4MTUwfQ.ggVoKRZercaUw65Lc4O68YJ0zlw7-f_bnUymQ_wmAIs

{
    "author": "Some Dude",
    "url": "blog.blog.com",
    "title": "testing out migrations update",
    "year": "2023"
}
############

DELETE http://localhost:3001/api/blogs/3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZvb0Bmb28uY29tIiwiaWQiOjEsImlhdCI6MTY3Nzc4ODE1MCwiZXhwIjoxNjc4MTQ4MTUwfQ.ggVoKRZercaUw65Lc4O68YJ0zlw7-f_bnUymQ_wmAIs

#########

PUT http://localhost:3001/api/blogs/15
Content-Type: application/json

{
    "likes": 441
}

#########

GET http://localhost:3001/api/blogs?search=react