GET http://localhost:3001/api/blogs

###############

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhckBiYXIuYmFyIiwiaWQiOjIsImlhdCI6MTY3NzYwNDQ3MiwiZXhwIjoxNjc3OTY0NDcyfQ.i0WT-axKaHuICTR56_3CSaxrDULkrpB2xAUyVNopLnU

{
    "author": "react guru",
    "url": "test.test",
    "title": "testing for exercise 13.14"
}
############

DELETE http://localhost:3001/api/blogs/12
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhckBiYXIuYmFyIiwiaWQiOjIsImlhdCI6MTY3NzUxNDY0MSwiZXhwIjoxNjc3ODc0NjQxfQ.jmBea0oRnT8SFvzu_dGjFzKL1k2VrGhgxNv36i7cXys

#########

PUT http://localhost:3001/api/blogs/7
Content-Type: application/json

{
    "likes": 1112
}

#########

GET http://localhost:3001/api/blogs?search=react