GET http://localhost:3001/api/readinglists

###########

POST http://localhost:3001/api/readinglists
Content-Type: application/json

{
    "blogId": 4,
    "userId": 1
}

##########

PUT http://localhost:3001/api/readinglists/4
Content-Type: application/json
Authorization: bearer
    
{
    "read": true
}