GET http://localhost:3001/api/users

###############

POST http://localhost:3001/api/users
Content-Type: application/json

{
   "username": "foo@foo.foo",
   "name": "Foo McFooson"
}
############


#########

PUT http://localhost:3001/api/users/foo@foo.foo
Content-Type: application/json

{
    "username": "foo@foo.com"
}


#########

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "foo@foo.com",
    "password": "password"
}