GET http://localhost:3001/api/users

###############

POST http://localhost:3001/api/users
Content-Type: application/json

{
   "username": "bar@bar.bar",
   "name": "Bar McBarson"
}
############


#########

PUT http://localhost:3001/api/users/foo@foo.foo
Content-Type: application/json

{
    "username": "foo@foo.foo"
}


#########

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "foo@foo.foo",
    "password": "password"
}